# pip install docker-compose
version: '3.3'
services:

  joomla-db:
    image: percona:latest
    container_name: joomla-db
    # restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - data-sql:/var/lib/mysql
    networks:
      - net-prod
    # deploy:
      # resources:
        # limits:
          # cpus: '0.5'
          # memory: 2048M
        # reservations:
          # cpus: '0.5'
          # memory: 1024M

  joomla-app:
    depends_on:
      - joomla-db
    image: rlagutinhub/joomla:201710091020
    container_name: joomla-app
    # restart: always
    env_file: .env
    environment:
      - PORTAL_VHOST_DIR=${PORTAL_VHOST_DIR}
      - PORTAL_VHOST_NAME=${PORTAL_VHOST_NAME}
      - PORTAL_MYSQL_HOSTNAME=${PORTAL_MYSQL_HOSTNAME}
      - PORTAL_MYSQL_USERNAME=${PORTAL_MYSQL_USERNAME}
      - PORTAL_MYSQL_PASSWORD=${PORTAL_MYSQL_PASSWORD}
      - PORTAL_MYSQL_DBNAME=${PORTAL_MYSQL_DBNAME}
      - URL_WWW_DATA=${URL_WWW_DATA}
      - URL_SQL_DATA=${URL_SQL_DATA}
    volumes:
      - data-www:/var/www/
    networks:
      - net-prod
    ports:
      - 80:80/tcp
    # deploy:
      # resources:
        # limits:
          # cpus: '0.5'
          # memory: 2048M
        # reservations:
          # cpus: '0.5'
          # memory: 1024M

volumes:
  data-sql:
    driver: local
  data-www:
    driver: local
networks:
  net-prod:
    driver: bridge
